apiVersion: v1 
kind: Pod 
metadata: 
  name: node-selector 
  labels: 
    purpose: "selector-demo"
spec: 
  nodeSelector:
    topology.kuberntes.io/zone: us-east-1a
  containers:
  - image: nginx
    name: nginx
  